### PR TITLE
Feat/Qb-1274: Genesis default/export value update

### PR DESCRIPTION
**Pull request by Xiong-stratos**

### CODE REVIEW

**Comment by tengfei-stratos** [comment]
Looks like the chain_id in evm section was not added automatically. Can you please check? Thanks

**Comment by tengfei-stratos** [comment]
and the `last_reported_epoch` field is not reset to 0

**Comment by Xiong-stratos** [comment]
OK I'll reset last_reported_epoch field in genesisupgrade tool, but not in this pr.

**Comment by Xiong-stratos** [comment]
> and the `last_reported_epoch` field is not reset to 0

Accroding to Alex's desicion, `last_reported_epoch`  field doesn't need to reset when export genesis.
I'll add the reset logic to genesis upgrade tool.

**Pull request merged**
